# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Premium Crunch
email: peter@premiumcrunch.com
description: > # this means to ignore newlines until "baseurl:"
  A sistersite of a yet to be announced website, don't waste your time perusing this domain.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://premiumcrunch.com" # the base hostname & protocol for your site
twitter_username: peterdmacdonald
github_username:  P373

# Build settings
markdown: kramdown
